# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_auto_20180811_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.BooleanField(default=None),
        ),
    ]
