# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
